# coding: utf-8

"""
    Flying Saucers

    This is for MSCS710 Project Course

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .user import User
