# coding: utf-8

"""
    Flying Saucers

    This is for MSCS710 Project Course

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.traffic_api import TrafficApi


class TestTrafficApi(unittest.TestCase):
    """ TrafficApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.traffic_api.TrafficApi()

    def tearDown(self):
        pass

    def test_output_graph(self):
        """
        Test case for output_graph

        Gives out a graph of how much traffic can be estimated
        """
        pass

    def test_predict_time(self):
        """
        Test case for predict_time

        Analysis of the model
        """
        pass


if __name__ == '__main__':
    unittest.main()
