# coding: utf-8

"""
    Flying Saucers

    This is for MSCS710 Project Course

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.user_api import UserApi


class TestUserApi(unittest.TestCase):
    """ UserApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.user_api.UserApi()

    def tearDown(self):
        pass

    def test_create_user(self):
        """
        Test case for create_user

        Create user
        """
        pass

    def test_delete_user(self):
        """
        Test case for delete_user

        Delete user
        """
        pass

    def test_get_user_by_name(self):
        """
        Test case for get_user_by_name

        Get user by user name
        """
        pass

    def test_login_user(self):
        """
        Test case for login_user

        Logs user into the system
        """
        pass

    def test_logout_user(self):
        """
        Test case for logout_user

        Logs out current logged in user session
        """
        pass

    def test_update_user(self):
        """
        Test case for update_user

        Updated user
        """
        pass


if __name__ == '__main__':
    unittest.main()
